name: macos
on: [push, pull_request]
jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rakudo/star@v2
      - run: zef --/test install .
      - run: zef test .
